runtime: python312

handlers:

- url: /styles
  static_dir: app/web/static/css

- url: /scripts
  static_dir: app/web/static/js

- url: /libs
  static_dir: app/web/static/lib

- url: /fonts
  static_dir: app/web/static/font

- url: /images
  static_dir: app/web/static/img

- url: /svgs
  static_dir: app/web/static/svg

- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 1
