
@apikey = 
@keywords = Computer Vision, Scopus, Machine Learning, Bibliometric
@date = 2021-2024
@scopus_id = SCOPUS_ID:85197125619
@search-fields = eid,prism:coverDate,prism:publicationName,citedby-count,prism:volume,dc:title,prism:doi,dc:identifier,author
@abstract-fields = dc:identifier,eid,dc:title,dc:description,prism:publicationName,citedby-count,prism:volume,prism:coverDate,prism:doi,dc:creator,authors


### Scopus Search API <https://dev.elsevier.com/documentation/ScopusSearchAPI.wadl>

GET https://api.elsevier.com/content/search/scopus?query=TITLE-ABS-KEY({{keywords}})&date={{date}}&suppressNavLinks=true&field={{search-fields}}
User-Agent: rest-client
Content-Type: application/json
Accept: application/json
X-ELS-APIKey: {{apikey}}


### Abstract Retrieval API <https://dev.elsevier.com/documentation/AbstractRetrievalAPI.wadl>

GET http://api.elsevier.com/content/abstract/scopus_id/{{scopus_id}}?field={{abstract-fields}}
User-Agent: rest-client
Content-Type: application/json
Accept: application/json
X-ELS-APIKey: {{apikey}}
