
@apikey =
@keywords = Images, Machine Learning, Artificial Inteligence, Computer Vision
@date = 2018-2023
@id = SCOPUS_ID:0037368024
@fields = dc:identifier,dc:title,prism:publicationName,prism:volume,prism:coverDate,prism:doi,citedby-count


### Scopus API - Search Articles

GET https://api.elsevier.com/content/search/scopus?query=TITLE-ABS-KEY({{keywords}})&field={{fields}}&date={{date}}&suppressNavLinks=true
User-Agent: rest-client
Content-Type: application/json
Accept: application/json
X-ELS-APIKey: {{apikey}}


### Scopus API - Get Article by Id

GET http://api.elsevier.com/content/abstract/scopus_id/{{id}}
User-Agent: rest-client
Content-Type: application/json
Accept: application/json
X-ELS-APIKey: {{apikey}}


### Local API - Search Articles

GET http://127.0.0.1:8000/scopus-searcher/api/search-articles?apikey={{apikey}}&keywords={{keywords}}
User-Agent: rest-client
Content-Type: application/json
Accept: application/json
X-ELS-APIKey: {{apikey}}
